// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtcobeycqaoxordfoqrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0Y29iZXljcWFveG9yZGZvcXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMTAzOTMsImV4cCI6MjA1Nzc4NjM5M30.ELx1AacaTgNsiJ5OHbzp-xMRMPZ5xJtww4DykTZsYd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);